package com.example.mgpjpawebapp06.controller;

import com.example.mgpjpawebapp06.model.Student;
import com.example.mgpjpawebapp06.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
//@CrossOrigin(value = "*")
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/")
    public String detteErRoden() {
        return "Du er i roden af mgpjpawebapp06";
    }

    @GetMapping("/students")
    public List<Student> students() {
        System.out.println("Liste af alle studenter");
        List<Student> lst = studentRepository.findAll();
        return lst;
    }

    @PostMapping("/student")
    @ResponseStatus(HttpStatus.CREATED)
    public Student postStudent(@RequestBody Student student) {
        System.out.println("Indsætter ny student");
        System.out.println(student);
        return studentRepository.save(student);
    }

    @GetMapping("/addstudent")
    public List<Student> addstudent() {
        Student std = new Student();
        std.setBorn(LocalDate.now());
        std.setBornTime(LocalTime.now());
        List<Student> lst = studentRepository.findAll();
        std.setName("Autogenerated size =" + lst.size());
        studentRepository.save(std);
        System.out.println("Student save =" + std.getName());
        return lst;
    }

}
